# Generated by Django 5.0.3 on 2024-04-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adminuser",
            fields=[
                ("admin_user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "AdminUser",
            },
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                ("auction_id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "starting_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "Auction",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Category",
            },
        ),
        migrations.CreateModel(
            name="Normaluser",
            fields=[
                ("normal_user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "NormalUser",
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("bid_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.adminuser",
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.auction",
                    ),
                ),
                (
                    "normal_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.normaluser",
                    ),
                ),
            ],
            options={
                "db_table": "Bid",
            },
        ),
        migrations.CreateModel(
            name="Paymentinfo",
            fields=[
                (
                    "payment_info_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("payment_method", models.CharField(max_length=255)),
                ("billing_address", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.normaluser",
                    ),
                ),
            ],
            options={
                "db_table": "PaymentInfo",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("phone_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.category",
                    ),
                ),
            ],
            options={
                "db_table": "Phone",
            },
        ),
        migrations.AddField(
            model_name="auction",
            name="phone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dbgroup7_app.phone",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("report_content", models.TextField()),
                ("timestamp", models.DateTimeField()),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": "Report",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_date", models.DateTimeField()),
                (
                    "auction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.auction",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.normaluser",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transaction_seller_set",
                        to="dbgroup7_app.normaluser",
                    ),
                ),
            ],
            options={
                "db_table": "Transaction",
            },
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                ("shipping_id", models.AutoField(primary_key=True, serialize=False)),
                ("shipping_address", models.CharField(max_length=255)),
                ("shipping_date", models.DateTimeField()),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "Shipping",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.normaluser",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dbgroup7_app.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "Feedback",
            },
        ),
    ]
