# Generated by Django 5.0.3 on 2024-04-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbgroup7_app", "0003_alter_feedback_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinfo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dbgroup7_app.normaluser",
            ),
        ),
    ]
