# Generated by Django 5.0.3 on 2024-04-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbgroup7_app", "0004_alter_paymentinfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_as_buyer",
                to="dbgroup7_app.normaluser",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_as_seller",
                to="dbgroup7_app.normaluser",
            ),
        ),
    ]
